[package]
name = "rinux-fs"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
rinux-helper.workspace = true
rinux-bindings.workspace = true

[build-dependencies]
bindgen.workspace = true